### PR TITLE
Fix seeds file

### LINKED ISSUE #162: DB seed fails due to invalid attributes
The DB seed failed upon setting up the codebase for the first time due to a `ActiveModel::UnknownAttributeError: unknown attribute 'email' for Partner.` It appears the `email` attribute and the Devise attribute `password` were removed from the `Partner` model in [this commit](https://github.com/rubyforgood/partner/commit/b136e0781b8b19060288599823d6ba369f76849f). Removing those attributes should fix the seed file.

### PR DESCRIPTION
**Pull request by samudary**
Resolves #162 

### Description

- No longer references email and password attributes on the Partner model during database seeding
- Cleans up duplicate name attribute

### Type of change

* Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Ran `db:seed` task successfully

### CODE REVIEW

**Comment by benreyn** [comment]
Thanks for this PR @samudary! I really appreciate it. This was an oversight on my part when merging #140. I think we also need to create one user for each Partner in the seeds file in order for the seeded partners to login. Could you make that change on this branch?

File: spec/lib/tasks/db_seed_spec.rb [hunk 1]
```diff
@@ -0,0 +1,7 @@
+require "spec_helper"
```
Comment (benreyn) [inline spec/lib/tasks/db_seed_spec.rb]: Great call adding this test! Now we'll know if we break these in the future.
